/**
 * Search synonyms, keyed by a (singular, lowercase) word that appears in icon names.
 *
 * Every icon gets the words of its own name as keywords; the entries below add the terms people
 * actually type when they look for it ("trash" for Delete, "gear" for Settings...). A word without
 * an entry here simply keeps the terms extracted from its name.
 *
 * @type {Readonly<Record<string, readonly string[]>>}
 */
export const SYNONYMS = {
	// Actions
	add: ['plus', 'new', 'create', 'insert'],
	subtract: ['minus', 'remove', 'less'],
	dismiss: ['close', 'cancel', 'x', 'clear', 'remove', 'exit'],
	checkmark: ['check', 'tick', 'done', 'ok', 'confirm', 'accept', 'yes'],
	delete: ['trash', 'bin', 'remove', 'garbage', 'discard'],
	edit: ['pencil', 'write', 'modify', 'change', 'rename'],
	save: ['disk', 'floppy', 'store', 'keep'],
	copy: ['duplicate', 'clone'],
	cut: ['scissors', 'trim'],
	paste: ['clipboard', 'insert'],
	search: ['find', 'magnify', 'lookup', 'query', 'zoom'],
	filter: ['funnel', 'refine', 'narrow'],
	sort: ['order', 'arrange', 'rank'],
	download: ['save', 'get', 'import', 'down'],
	upload: ['send', 'export', 'publish', 'up'],
	open: ['launch', 'expand', 'unfold'],
	more: ['menu', 'overflow', 'ellipsis', 'dots', 'kebab'],
	refresh: ['reload', 'update', 'renew', 'sync'],
	sync: ['refresh', 'synchronize', 'reload'],
	zoom: ['magnify', 'scale', 'resize'],
	cursor: ['pointer', 'mouse', 'select', 'click'],
	pin: ['pushpin', 'attach', 'stick', 'favorite'],
	bookmark: ['save', 'favorite', 'flag', 'mark'],
	flag: ['report', 'mark', 'banner'],
	tag: ['label', 'price', 'badge'],
	link: ['chain', 'url', 'hyperlink', 'connect'],
	share: ['send', 'export', 'social'],
	undo: ['revert', 'back', 'rollback'],
	redo: ['repeat', 'forward', 'reapply'],
	rotate: ['turn', 'spin', 'flip', 'orientation'],
	scan: ['barcode', 'qr', 'capture', 'read'],
	select: ['choose', 'pick', 'highlight'],
	drag: ['move', 'grab', 'reorder', 'handle'],
	lightning: ['bolt', 'flash', 'power', 'fast', 'electric'],
	flash: ['bolt', 'lightning', 'power', 'fast'],
	eye: ['view', 'visible', 'visibility', 'show', 'watch', 'preview'],
	off: ['disabled', 'disable', 'mute', 'hidden', 'slash', 'none'],
	on: ['enabled', 'enable', 'active'],
	multiple: ['many', 'several', 'group', 'stack', 'copies'],
	// Status & symbols
	warning: ['caution', 'alert', 'danger', 'triangle', 'attention'],
	error: ['fail', 'failure', 'problem', 'wrong'],
	info: ['information', 'about', 'details', 'help'],
	question: ['help', 'support', 'faq', 'unknown'],
	prohibited: ['forbidden', 'block', 'ban', 'not allowed', 'no'],
	important: ['exclamation', 'priority', 'urgent'],
	star: ['favorite', 'rating', 'rate', 'favourite', 'bookmark'],
	heart: ['like', 'love', 'favorite', 'health'],
	thumb: ['like', 'dislike', 'vote', 'approve'],
	emoji: ['smiley', 'face', 'smile', 'reaction', 'emoticon'],
	circle: ['round', 'dot', 'ring'],
	square: ['box', 'rectangle'],
	rectangle: ['box', 'square'],
	diamond: ['rhombus', 'gem'],
	cube: ['3d', 'box', 'object', 'block'],
	shape: ['geometry', 'figure', 'form'],
	// Arrows & navigation
	arrow: ['direction', 'pointer', 'navigate'],
	chevron: ['arrow', 'caret', 'angle', 'expand', 'collapse'],
	caret: ['arrow', 'triangle', 'dropdown'],
	left: ['west', 'previous', 'back'],
	right: ['east', 'next', 'forward'],
	up: ['north', 'raise', 'increase'],
	down: ['south', 'lower', 'decrease'],
	forward: ['next', 'skip', 'advance'],
	back: ['previous', 'return', 'prior'],
	ltr: ['left to right'],
	rtl: ['right to left'],
	navigation: ['gps', 'direction', 'location', 'route'],
	// People & communication
	person: ['user', 'account', 'profile', 'human', 'member'],
	people: ['users', 'team', 'group', 'community', 'persons'],
	contact: ['person', 'address', 'book', 'card'],
	avatar: ['profile', 'user', 'picture'],
	account: ['profile', 'user', 'login', 'identity'],
	group: ['team', 'people', 'collection'],
	hand: ['gesture', 'palm', 'wave', 'touch'],
	mail: ['email', 'envelope', 'message', 'letter', 'inbox'],
	chat: ['message', 'conversation', 'speech', 'bubble', 'talk', 'comment'],
	comment: ['note', 'feedback', 'message', 'bubble', 'review'],
	call: ['phone', 'telephone', 'dial', 'ring'],
	phone: ['mobile', 'smartphone', 'cell', 'call', 'device'],
	send: ['submit', 'paper plane', 'share', 'post'],
	alert: ['bell', 'notification', 'notify', 'reminder', 'alarm'],
	megaphone: ['announce', 'broadcast', 'promote', 'speaker'],
	// Documents
	document: ['file', 'page', 'doc', 'paper', 'sheet'],
	file: ['document', 'page', 'doc', 'attachment'],
	folder: ['directory', 'files', 'organize', 'collection'],
	page: ['document', 'sheet', 'paper'],
	note: ['memo', 'sticky', 'write'],
	notebook: ['journal', 'diary', 'notes'],
	book: ['read', 'library', 'manual', 'guide'],
	clipboard: ['copy', 'paste', 'board', 'task'],
	archive: ['box', 'store', 'backup', 'zip'],
	attach: ['paperclip', 'attachment', 'clip'],
	newspaper: ['news', 'article', 'press', 'blog'],
	// Text & layout
	text: ['type', 'font', 'typography', 'words', 'letters'],
	font: ['typeface', 'typography', 'text'],
	bold: ['strong', 'heavy'],
	italic: ['emphasis', 'slant'],
	underline: ['line', 'under'],
	strikethrough: ['cross out', 'delete', 'line'],
	list: ['bullets', 'items', 'menu', 'rows'],
	bullet: ['list', 'point', 'dot'],
	number: ['numeric', 'digit', 'count', 'ordered'],
	align: ['alignment', 'justify', 'position'],
	indent: ['tab', 'offset', 'margin'],
	quote: ['citation', 'blockquote', 'speech'],
	translate: ['language', 'localize', 'locale'],
	table: ['grid', 'spreadsheet', 'data', 'cells'],
	column: ['vertical', 'col', 'table'],
	row: ['horizontal', 'table', 'line'],
	layout: ['arrange', 'structure', 'template'],
	grid: ['tiles', 'apps', 'matrix', 'layout'],
	panel: ['pane', 'sidebar', 'drawer', 'section'],
	window: ['app', 'screen', 'frame', 'browser'],
	split: ['divide', 'separate', 'columns'],
	tab: ['page', 'browser', 'navigation'],
	header: ['top', 'title', 'heading'],
	// Devices
	desktop: ['computer', 'pc', 'monitor', 'screen'],
	laptop: ['computer', 'notebook', 'pc'],
	tablet: ['ipad', 'device', 'mobile'],
	screen: ['display', 'monitor', 'desktop'],
	battery: ['power', 'charge', 'energy', 'level'],
	keyboard: ['keys', 'type', 'input'],
	mouse: ['pointer', 'cursor', 'click'],
	usb: ['plug', 'drive', 'connector', 'port'],
	headset: ['headphones', 'support', 'audio'],
	watch: ['smartwatch', 'wearable', 'clock', 'time'],
	printer: ['print', 'paper', 'output'],
	print: ['printer', 'paper', 'output'],
	cellular: ['signal', 'mobile', 'network', 'bars', 'data'],
	plug: ['power', 'connector', 'socket', 'electric'],
	power: ['on', 'off', 'energy', 'shutdown', 'electric'],
	charge: ['battery', 'power', 'plug'],
	wifi: ['wireless', 'network', 'internet', 'signal'],
	// Media
	video: ['film', 'movie', 'clip', 'camera', 'record'],
	camera: ['photo', 'picture', 'capture', 'snapshot'],
	image: ['picture', 'photo', 'gallery', 'img'],
	photo: ['picture', 'image', 'camera', 'gallery'],
	music: ['audio', 'song', 'note', 'sound', 'melody'],
	play: ['start', 'run', 'resume', 'video'],
	pause: ['hold', 'wait', 'break'],
	stop: ['end', 'halt', 'square'],
	record: ['capture', 'rec', 'dot'],
	speaker: ['audio', 'sound', 'volume', 'loudspeaker'],
	mic: ['microphone', 'voice', 'record', 'audio'],
	volume: ['sound', 'audio', 'speaker', 'loud'],
	game: ['play', 'controller', 'gaming', 'fun'],
	controller: ['gamepad', 'game', 'joystick', 'xbox'],
	trophy: ['award', 'winner', 'prize', 'cup', 'achievement'],
	// Places & business
	home: ['house', 'main', 'start', 'dashboard'],
	building: ['office', 'city', 'company', 'enterprise'],
	globe: ['world', 'earth', 'web', 'internet', 'language', 'international'],
	location: ['map', 'pin', 'place', 'gps', 'marker', 'position'],
	map: ['location', 'route', 'navigate', 'atlas'],
	store: ['shop', 'market', 'retail', 'storefront'],
	cart: ['shopping', 'basket', 'checkout', 'buy', 'purchase'],
	bag: ['shopping', 'purchase', 'handbag'],
	money: ['cash', 'currency', 'dollar', 'finance', 'payment'],
	card: ['credit', 'payment', 'bank', 'debit', 'tile'],
	wallet: ['money', 'payment', 'purse'],
	briefcase: ['work', 'job', 'business', 'portfolio', 'bag'],
	certificate: ['award', 'diploma', 'badge', 'verified'],
	gift: ['present', 'reward', 'surprise'],
	receipt: ['invoice', 'bill', 'purchase', 'ticket'],
	bank: ['finance', 'money', 'institution'],
	coin: ['money', 'currency', 'cash', 'token'],
	// Data & dev
	data: ['analytics', 'statistics', 'chart', 'metrics'],
	chart: ['graph', 'analytics', 'statistics', 'plot', 'diagram'],
	pulse: ['heartbeat', 'activity', 'rate', 'health'],
	trending: ['growth', 'increase', 'analytics', 'trend'],
	database: ['db', 'storage', 'sql', 'data', 'server'],
	code: ['developer', 'programming', 'dev', 'script', 'html'],
	bug: ['issue', 'error', 'debug', 'insect'],
	terminal: ['console', 'command', 'cli', 'shell', 'prompt'],
	branch: ['git', 'fork', 'version', 'merge'],
	flow: ['process', 'workflow', 'diagram', 'chart'],
	server: ['host', 'backend', 'machine', 'data center'],
	cloud: ['online', 'storage', 'sky', 'backup', 'saas'],
	// Security
	lock: ['secure', 'private', 'password', 'padlock', 'protect'],
	shield: ['security', 'protect', 'guard', 'defense', 'safe'],
	key: ['password', 'access', 'unlock', 'security'],
	fingerprint: ['biometric', 'touch id', 'identity', 'security'],
	password: ['secret', 'lock', 'login', 'credentials'],
	// Time
	calendar: ['date', 'schedule', 'event', 'day', 'month', 'agenda'],
	clock: ['time', 'watch', 'hour', 'schedule'],
	timer: ['stopwatch', 'countdown', 'time', 'clock'],
	alarm: ['clock', 'alert', 'wake', 'reminder'],
	history: ['recent', 'past', 'clock', 'undo', 'log'],
	// Weather & nature
	weather: ['forecast', 'climate', 'sky'],
	sun: ['sunny', 'light', 'brightness', 'day', 'daylight'],
	moon: ['night', 'dark', 'lunar', 'sleep'],
	rain: ['rainy', 'shower', 'drizzle', 'wet'],
	snow: ['snowflake', 'cold', 'winter', 'frost'],
	temperature: ['thermometer', 'heat', 'hot', 'cold', 'degrees'],
	fire: ['flame', 'hot', 'burn', 'trending'],
	leaf: ['plant', 'eco', 'nature', 'green'],
	// Travel & transport
	vehicle: ['car', 'transport', 'automobile'],
	car: ['vehicle', 'auto', 'automobile', 'drive'],
	airplane: ['plane', 'flight', 'travel', 'aircraft', 'airport'],
	bus: ['transport', 'public', 'vehicle'],
	train: ['rail', 'railway', 'transport', 'subway'],
	rocket: ['launch', 'startup', 'space', 'boost'],
	// Food & health
	food: ['meal', 'eat', 'restaurant', 'dining'],
	drink: ['beverage', 'glass', 'cup'],
	coffee: ['cup', 'cafe', 'drink', 'tea'],
	health: ['medical', 'wellness', 'care', 'heart'],
	// Design & tools
	paint: ['color', 'brush', 'fill', 'art', 'draw'],
	pen: ['write', 'ink', 'draw', 'sign', 'edit'],
	pencil: ['write', 'draw', 'edit', 'sketch'],
	brush: ['paint', 'draw', 'art'],
	color: ['palette', 'paint', 'hue', 'fill', 'theme'],
	crop: ['trim', 'cut', 'resize', 'image'],
	ruler: ['measure', 'size', 'length'],
	highlight: ['marker', 'emphasis', 'text'],
	settings: ['gear', 'cog', 'preferences', 'options', 'configuration', 'config'],
	wrench: ['tool', 'fix', 'repair', 'settings', 'spanner'],
	toolbox: ['tools', 'kit', 'utilities'],
	// AI & productivity
	sparkle: ['ai', 'magic', 'copilot', 'new', 'shine', 'star', 'effects'],
	bot: ['robot', 'ai', 'assistant', 'chatbot', 'automation'],
	brain: ['ai', 'mind', 'intelligence', 'think', 'idea'],
	copilot: ['ai', 'assistant', 'help'],
	agent: ['ai', 'bot', 'assistant'],
	lightbulb: ['idea', 'tip', 'hint', 'bulb', 'suggestion', 'light'],
	task: ['todo', 'checklist', 'work', 'item', 'job'],
	checkbox: ['check', 'tick', 'todo', 'form'],
	app: ['application', 'program', 'software'],
	slide: ['presentation', 'powerpoint', 'deck'],
	board: ['kanban', 'whiteboard', 'planner'],
	target: ['goal', 'aim', 'objective', 'bullseye'],
	// Accessibility
	accessibility: ['a11y', 'accessible', 'disability', 'inclusive'],
	wheelchair: ['accessible', 'disability', 'mobility'],
	braille: ['blind', 'accessibility', 'touch'],
	hearing: ['ear', 'deaf', 'audio', 'accessibility'],
	caption: ['subtitle', 'cc', 'closed captions', 'accessibility']
};
